export const ACTION_TEMPLATES_COLLECTION = 'actionTemplates'
export const USERS_COLLECTION = 'users'
export const PROJECTS_COLLECTION = 'projects'
export const PROJECTS_ENVIRONMENTS_COLLECTION = 'environments'
export const SYSTEM_SETTINGS_COLLECTION = 'system_settings'
export const USER_API_KEYS_SUBCOLLECTION = 'api_keys'
