steps:
# Build Fireadmin App Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fireadmin', '.']
  timeout: 500s
# Push App Image To Container Registry (Fireadmin uses this)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fireadmin']
  timeout: 500s
images: ['gcr.io/$PROJECT_ID/fireadmin']
