export default {
  login: 'Login',
  signup: 'Signup',
  createProject: 'Create Project',
  deleteProject: 'Delete Project',
  bucketAction: 'Storage Bucket Action',
  createEnvironment: 'Create Environment',
  updateEnvironment: 'Update Environment',
  deleteEnvironment: 'Delete Environment',
  createActionTemplate: 'Create Action Template',
  updateActionTemplate: 'Update Action Template',
  deleteActionTemplate: 'Delete Action Template',
  addRole: 'Add Role',
  updateRole: 'Update Role',
  removeRole: 'Delete Role',
  updatePermission: 'Update Permission',
  deletePermission: 'Delete Permission',
  requestActionRun: 'Request Action Run',
  addCollaborator: 'Add Collaborator',
  removeCollaborator: 'Remove Collaborator',
  deleteRole: 'Delete Role',
  denyMessagingPermission: 'Deny Messaging Permissions',
  invalidTemplateRunAttempt: 'Invalid Template Run Attempt'
}
