export const ACTION_TEMPLATES_PATH = 'actionTemplates'
export const ACTIONS_PATH = 'actions'
export const ACTION_RUNNER_REQUESTS_PATH = 'requests/actionRunner'
export const ACTION_RUNNER_RESPONSES_PATH = 'responses/actionRunner'
export const DISPLAY_NAMES_PATH = 'displayNames'
export const PROJECTS_COLLECTION = 'projects'
export const USERS_COLLECTION = 'users'
