export const ACTION_RUNNER_EVENT_PATH = 'actionRunner'
export const ACTION_RUNNER_REQUESTS_PATH = `requests/${ACTION_RUNNER_EVENT_PATH}`
export const ACTION_RUNNER_RESPONSES_PATH = `responses/${ACTION_RUNNER_EVENT_PATH}`
