export declare const DISPLAY_NAMES_PATH = "displayNames";
export declare const USERS_PATH = "users";
export declare const SESSIONS_PATH = "sessions";
export declare const PROJECTS_PATH = "projects";
export declare const SEARCH_PATH = "search";
export declare const SERVICE_ACCOUNTS_PATH = "serviceAccounts";
export declare const PRESENCE_PATH = "presence";
export declare const VERSION_INFO_PATH = "versionInfo";
export declare const ACTION_RUNNER_EVENT_PATH = "actionRunner";
export declare const CUSTOM_STEPS_PATH = "actionTemplates/customSteps";
export declare const ACTION_RUNNER_REQUESTS_PATH: string;
export declare const ACTION_RUNNER_RESPONSES_PATH: string;
