import { FireadminConfig } from './types/index';
import { loginWithApiKey } from './auth';
import Project from './Project';
import Projects from './Projects';
import ActionRequest from './ActionRequest';
import ActionTemplates from './ActionTemplates';
import ActionTemplate from './ActionTemplate';
import Users from './Users';
import User from './User';
import { ActionEnvironmentSetting, ActionSettings, ActionInputSetting, CustomActionStepSetting } from './types/Action';
export declare function initialize(fireadminConfig: FireadminConfig): void;
export { Projects, Project, Users, User, ActionTemplates, ActionTemplate, ActionRequest, loginWithApiKey, ActionEnvironmentSetting, ActionSettings, ActionInputSetting, CustomActionStepSetting };
export default initialize;
