name: Test Hosted App

on: 
  pull_request:
    branches:
      - tests-*
    paths-ignore:
      - 'docs/**'

jobs:
  ui-tests:
    name: UI Test Hosted App
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        # Run multiple copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache npm dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-main-${{ hashFiles('**/yarn.lock') }}

      - name: Get Library Versions For Binary Caching
        id: dep-versions
        run: |
          echo "::set-output name=cypress::$(cat package.json | jq -r .devDependencies.cypress)"

      - name: Cache Cypress Binary
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ steps.dep-versions.outputs.cypress }}

      # Install is run separately from test so that dependencies are available
      # for other steps like Get Project Info and build test environment config
      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
          $(yarn bin)/cypress verify

      - name: Archive Error Logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test-error-logs
          path: yarn-error.log

      # Cypress action manages installing/caching npm dependencies and Cypress binary.
      # Because of "record" and "parallel" parameters these containers will load
      # balance all found tests among themselves. The step tests a version of the app
      # which is running locally in the container on port 3000
      - name: Cypress Run
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          cache-key: ${{ runner.os }}-verify-cypress-${{ hashFiles('**/yarn.lock') }}
          browser: chrome
          parallel: true
          record: true
          headless: true
          group: 'UI Tests'
        env:
          # TODO: Look into if this can be moved to an npm script
          TZ: America/Los_Angeles
          CI: true
          # Pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCLOUD_PROJECT: fireadmin-stage
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          CYPRESS_baseUrl: https://fireadmin-stage.firebaseapp.com