name: Verify Docs

on: 
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-deploy.yml'

jobs:
  verify-build:
    name: Verify + Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Dependencies
        uses: actions/cache@v2.1.5
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-docs-${{ hashFiles('**/yarn.lock') }}

      # Removed due to causing failed builds
      # - name: Cache Gatsby Build
      #   uses: actions/cache@v2.1.5
      #   with:
      #     path: docs/.cache
      #     key: ${{ runner.os }}-docs-build

      - name: Install Dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0 # Skip installing of cypress
        run: |
          yarn --cwd docs install --frozen-lockfile

      - name: Verify
        run: |
          yarn --cwd docs lint

      - name: Build
        run: |
          yarn --cwd docs build

