name: Verify App

on: [pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - uses: actions/cache@v1
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0 # Skip installing of cypress
        run: |
          yarn install --frozen-lockfile --cache-folder .yarn
          yarn --cwd functions install --frozen-lockfile --cache-folder .yarn

      - name: Verify App
        run: |
          yarn build:config # Create env specific src/config.js
          yarn lint:app # Check for lint in app code
          yarn build # Build app bundles

      - name: Verify Functions
        run: |
          yarn lint:functions # Check for lint within functions
          yarn --cwd functions test:cov # Run unit tests with coverage
          yarn --cwd functions build